adform/stream-loader

.github/workflows/build.yml
stream-loader-core/src/main/scala/com/adform/streamloader/KafkaContext.scala
stream-loader-core/src/main/scala/com/adform/streamloader/KafkaSource.scala
stream-loader-core/src/test/scala/com/adform/streamloader/MockKafkaContext.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/Docker.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/storage/StorageBackend.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/storage/VerticaStorageBackend.scala
stream-loader-tests/src/main/scala/com/adform/streamloader/loaders/Vertica.scala
stream-loader-vertica/src/main/scala/com/adform/streamloader/vertica/ExternalOffsetVerticaFileStorage.scala

Previously the external offset Vertica storage would store offsets for each table being loaded in the offset table, now it stores the consumer group instead of the table being loaded. In order to make this work, we also add a `consumerGroup` member to `KafkaContext`, which allows sinks to know the consumer group ID.
Also fix CI so that it runs on branches and remove legacy network setup in Docker integration tests.

Replace table with consumer group in the Vertica offset table

---

.github/workflows/publish.yml

In the v2 of `actions/checkout`, setting the token is no longer necessary, so I created a new config-less action to just set the git user: https://github.com/fregante/setup-git-user

Replace `fregante/setup-git-token` with `setup-git-user`

---

.github/workflows/build.yml
.gitignore
build.sbt
project/build.properties
project/plugins.sbt
stream-loader-hadoop/src/main/scala/com/adform/streamloader/hadoop/parquet/AvroParquetFileBuilderFactory.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/ClickHouse.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/Hdfs.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/Kafka.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/S3.scala

Version updates:
- sbt 1.5.0, fixed deprecation warnings,
- scala 2.13.5,
- all other libraries and test docker images.
Also disabled coursier, as referencing jars from external URLs (needed for the vertica JDBC driver) seems broken, see https://github.com/sbt/sbt/issues/5418.

Bump versions

---

.github/workflows/build.yml
build.sbt
project/build.properties
project/plugins.sbt
stream-loader-core/src/main/scala/com/adform/streamloader/batch/RecordBatchingSinker.scala
stream-loader-core/src/main/scala/com/adform/streamloader/file/FileRecordBatch.scala
stream-loader-core/src/main/scala/com/adform/streamloader/file/PartitionedFileRecordBatch.scala
stream-loader-core/src/main/scala/com/adform/streamloader/model/RecordBatch.scala
stream-loader-core/src/main/scala/com/adform/streamloader/util/KafkaMetricsReporter.scala
stream-loader-core/src/test/scala/com/adform/streamloader/batch/RecordBatchingSinkerTest.scala
stream-loader-core/src/test/scala/com/adform/streamloader/file/PartitioningFileRecordBatcherTest.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/ClickHouse.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/S3.scala

During the [refactoring](https://github.com/adform/stream-loader/pull/8/files) from file batches to abstract record batches the file delete functionality was removed ([this part](https://github.com/adform/stream-loader/pull/8/files#diff-cb661d321e494e50914b29b48655ece6ee7a728d5ddfd3fc931c4f149bff7da7L82-L84)), so now the loaders keep producing files under `/tmp` indefinitely.
We now introduce a `discard` method on a `RecordBatch` that is called after a successful commit to storage. The current file based batches implement it as file deletion.
Also, bump all versions and use JDK 11 during the build, as the latest Hikari version only works with JDK 11.

Implement batch discarding

---

.github/workflows/build.yml
build.sbt
project/plugins.sbt
stream-loader-core/src/main/scala/com/adform/streamloader/KafkaSource.scala
stream-loader-core/src/main/scala/com/adform/streamloader/batch/RecordBatcher.scala
stream-loader-core/src/main/scala/com/adform/streamloader/batch/RecordBatchingSinker.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/ClickHouse.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/S3.scala

- added `close()` to the `RecordBatcher` interface
- added ability to subscribe to a `Pattern` of Kafka topics
- bumped all versions

Add batcher close hook, allow subscribing to topic pattern

---

stream-loader-core/src/main/scala/com/adform/streamloader/PartitionGroupingSink.scala
stream-loader-core/src/test/scala/com/adform/streamloader/PartitionGroupingSinkTest.scala

The partition grouping sink had a bug where it would miss previously assigned partitions if new partitions to the existing group got assigned. E.g. consider a sink that groups by topic, which gets assigned partitions `(test, 0)` and `(test, 1)`. It would create a single group `test` and assign partitions `0` and `1` to it. If it now got assigned `(test, 2)` the sink would destroy the existing group and create a new one with the partition `2` only, missing the previously assigned partitions `0` and `1`.
The bug would cause loaders to crash with a `NoSuchElementException` exception [here](https://github.com/adform/stream-loader/blob/4f2257b98678df54455ed2623cae353fa209d2d1/stream-loader-core/src/main/scala/com/adform/streamloader/PartitionGroupingSink.scala#L139). I suspect we never …

Fix partition assignment bug

---

build.sbt
project/build.properties
project/plugins.sbt

Bumping `s3` and `clickhouse` dependencies requires more work, so skipping for now.

Bump libraries

---

stream-loader-core/src/main/scala/com/adform/streamloader/KafkaSource.scala
stream-loader-core/src/main/scala/com/adform/streamloader/PartitionGroupSinker.scala
stream-loader-core/src/main/scala/com/adform/streamloader/PartitionGroupingSink.scala
stream-loader-core/src/main/scala/com/adform/streamloader/Sink.scala
stream-loader-core/src/main/scala/com/adform/streamloader/WatermarkProvider.scala
stream-loader-core/src/main/scala/com/adform/streamloader/batch/RecordBatchingSink.scala
stream-loader-core/src/main/scala/com/adform/streamloader/batch/RecordBatchingSinker.scala
stream-loader-core/src/main/scala/com/adform/streamloader/model/Record.scala
stream-loader-core/src/test/scala/com/adform/streamloader/MaxWatermarkProviderTest.scala
stream-loader-core/src/test/scala/com/adform/streamloader/PartitionGroupingSinkTest.scala
stream-loader-core/src/test/scala/com/adform/streamloader/batch/RecordBatchingSinkerTest.scala

Currently the `Source` and `Sink` interfaces are not symmetric in how they deal with watermarks, i.e. we have:
```scala
class KafkaSource {
def seek(partition: TopicPartition, position: StreamPosition): Unit
def poll(): Iterable[ConsumerRecord[Array[Byte], Array[Byte]]]
}
```
and
```scala
trait Sink {
def assignPartitions(partitions: Set[TopicPartition]): Map[TopicPartition, Option[StreamPosition]]
def write(record: ConsumerRecord[Array[Byte], Array[Byte]]): Unit
}
```
where the `StreamPosition` includes the Kafka consumer record plus the watermark. The source currently produces raw Kafka records without watermarks, but sinks are required to return the committed offset together with a watermark - they both get passed down to the source when initializing, but the watermark is not used …

Move watermark tracking to source

---

stream-loader-core/src/main/scala/com/adform/streamloader/model/StreamInterval.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/PartitionGroupSinker.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/PartitionGroupingSink.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/RewindingPartitionGroupSinker.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/Sink.scala
stream-loader-core/src/main/scala/com/adform/streamloader/source/KafkaContext.scala
stream-loader-core/src/test/scala/com/adform/streamloader/model/Generators.scala
stream-loader-core/src/test/scala/com/adform/streamloader/sink/RewindingPartitionGroupSinkerTest.scala
stream-loader-core/src/test/scala/com/adform/streamloader/sink/file/PartitioningFileRecordBatcherTest.scala
stream-loader-core/src/test/scala/com/adform/streamloader/source/MaxWatermarkProviderTest.scala
stream-loader-core/src/test/scala/com/adform/streamloader/source/MockKafkaContext.scala
stream-loader-core/src/test/scala/com/adform/streamloader/util/MockTimeProvider.scala
stream-loader-core/src/test/scala/com/adform/streamloader/util/TestExtensions.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/storage/StorageBackend.scala

Add an implementation for a `RewindingPartitionGroupSinker` that wraps another `Sinker` and rewinds the streams backwards during initialization. For the whole "rewind period" records are only being "touched" and afterwards they get forwarded to the base sinker. This can be used for implementing stateful sinks that need to do some kind of a "warm-up" before writing, e.g. building up a de-duplication cache.

Add a rewinding sinker implementation

---

.github/workflows/build.yml
.github/workflows/publish.yml
build.sbt
project/build.properties
project/plugins.sbt
stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/ClickHouseFileBuilder.scala
stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/ClickHouseFileRecordBatch.scala
stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/ClickHouseFileRecordBatcher.scala
stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/ClickHouseFileStorage.scala
stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/rowbinary/RowBinaryClickHouseFileBuilder.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/PartitionGroupingSink.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/RecordBatch.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/RecordBatchingSinker.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/file/PartitioningFileRecordBatcher.scala
stream-loader-core/src/main/scala/com/adform/streamloader/source/KafkaSource.scala
stream-loader-s3/src/test/scala/com/adform/streamloader/s3/MockS3.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/ClickHouseTests.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/ClickHouse.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/Kafka.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/S3.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/Vertica.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/storage/ClickHouseStorageBackend.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/storage/VerticaStorageBackend.scala
stream-loader-tests/src/main/scala/com/adform/streamloader/loaders/ClickHouse.scala
stream-loader-vertica/src/main/scala/com/adform/streamloader/vertica/ExternalOffsetVerticaFileStorage.scala
stream-loader-vertica/src/main/scala/com/adform/streamloader/vertica/InRowOffsetVerticaFileStorage.scala

Collection of small-to-medium changes:
- Bumped build to JDK 11
- Bump all GitHub action plugins
- Upgraded `sbt`, fixed all warnings in build
- Switched to coursier
- Upgraded `s3` sdk
- Switched to official Vertica docker image / jdbc driver, bumped them
- Switched to `bitnami/kafka` docker image, removed zookeeper, moved to KRaft mode
- Upgraded `clickhouse-jdbc` and switched to `com.clickhouse` package
- Added support for compression in ClickHouse
- Switched from `TrieMap` to `mutable.HashMap` in all single-threaded code
- Reverted to the `watermark.delay.ms` metric instead of `watermark.ms`
- Made internal `Metrics` objects private

Small improvements

---

stream-loader-core/src/main/scala/com/adform/streamloader/model/StreamRange.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/storage/TwoPhaseCommitBatchStorage.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/storage/TwoPhaseCommitMetadata.scala
stream-loader-core/src/test/scala/com/adform/streamloader/sink/batch/storage/MockTwoPhaseCommitFileStorage.scala
stream-loader-core/src/test/scala/com/adform/streamloader/sink/batch/storage/TwoPhaseCommitFileStorageTest.scala
stream-loader-core/src/test/scala/com/adform/streamloader/sink/batch/storage/TwoPhaseCommitMetadataTest.scala
stream-loader-hadoop/src/test/scala/com/adform/streamloader/hadoop/HadoopFileStorageTest.scala
stream-loader-s3/src/test/scala/com/adform/streamloader/s3/S3FileStorageTest.scala

The `TwoPhaseCommitBatchStorage` stores a JSON value in the Kafka offset [metadata](https://kafka.apache.org/31/javadoc/org/apache/kafka/clients/consumer/OffsetAndMetadata.html#metadata()) field during the staging step that can become relatively large in some scenarios. E.g. the HDFS loader with partitioning can try to stage something like the following:
```scala
val stagePath = "/user/hive/warehouse/database.db/table"
val destPath = "/user/hive/warehouse/database.db/table"
val s = MultiFileStaging(
Seq(
FileStaging(
s"$stagePath/6c7ea313-1ab8-443c-b96a-c5a8bd47f310.parquet",
s"$destPath/dt=20221201/6c7ea313-1ab8-443c-b96a-c5a8bd47f310.parquet"
),
FileStaging(
s"$stagePath/1971784a-3416-4d51-8b52-72bf191e5bc6.parquet",
s"$destPath/dt=20221202/1971784a-3416-4d51-8b52-72bf191e5bc6.parquet" …
```

Compress Kafka offset metadata

---

stream-loader-core/src/main/diagrams/core_class_hierarchy.puml

Class names were not correct in the class diagram

Fix typos in docs

---

build.sbt
stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/ClickHouseFileBuilder.scala
stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/ClickHouseFileRecordBatch.scala
stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/ClickHouseFileStorage.scala
stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/rowbinary/RowBinaryClickHouseFileBuilder.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/storage/TwoPhaseCommitBatchStorage.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/ClickHouse.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/Kafka.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/Vertica.scala

Expose Kafka commit metadata metrics per topic only, as the previous topic/partition combo produced way too much metrics (~30mb in our most extreme case).
Also bump versions.

Reduce Kafka offset commit metadata metric size

---

stream-loader-hadoop/src/main/scala/com/adform/streamloader/hadoop/HadoopFileStorage.scala

A single HDFS loader consuming multiple Kafka partitions to a single file will write identical `(staged_path, target_path)` staging information to the Kafka offset metadata for all partitions. If it crashes after staging it will attempt recovery for each partition and each of them will attempt to do the same move `staged_path` -> `target_path` - we only care if one of them succeeds, others will fail and can be safely ignored.
This PR fixes the current behavior that always throws an exception and fails.

Fix recovery bug in HDFS loader

---

build.sbt
project/plugins.sbt
stream-loader-clickhouse/src/main/scala/com/adform/streamloader/clickhouse/ClickHouseFileRecordBatcher.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/RecordBatch.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/RecordBatchingSinker.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/file/FileRecordBatcher.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/file/PartitioningFileRecordBatcher.scala
stream-loader-core/src/test/scala/com/adform/streamloader/sink/batch/RecordBatchingSinkerTest.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/ClickHouse.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/Kafka.scala
stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/S3.scala
stream-loader-vertica/src/main/scala/com/adform/streamloader/vertica/ExternalOffsetVerticaFileBatcher.scala
stream-loader-vertica/src/main/scala/com/adform/streamloader/vertica/InRowOffsetVerticaFileBatcher.scala

Addresses the issue described in https://github.com/adform/stream-loader/issues/30.
Refactor the abstract `RecordBatchBuilder` class and require implementers to define `addToBatch` that returns the number of records added to batch instead of relying on implementers overriding the `add` method. Now the `add` method only keeps track of record ranges and no longer does record counting, which previously was always assumed to be one per record - this is obviously not the case if implementations do filtering or exploding of records. The number of batched records is now exposed as a metric `records.batched`.
Also bump versions.

Add batched record metric

---

stream-loader-core/src/main/scala/com/adform/streamloader/sink/file/PartitionedFileRecordBatch.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/file/PartitioningFileRecordBatcher.scala
stream-loader-core/src/test/scala/com/adform/streamloader/sink/batch/RecordBatchBuilderTest.scala
stream-loader-core/src/test/scala/com/adform/streamloader/sink/file/PartitioningFileRecordBatcherTest.scala
stream-loader-hadoop/src/test/scala/com/adform/streamloader/hadoop/HadoopFileStorageTest.scala
stream-loader-s3/src/test/scala/com/adform/streamloader/s3/S3FileStorageTest.scala

Addresses issue #32.
The `PartitionedFileRecordBatch` class calculates the overall record range as `min/max` of the contained partition batches, however the issue is that partitions are formed after formatting records, which can potentially skip records thus ending up with an incomplete overall range. This PR contains a test case that illustrates the issue. A consequence of this is not committing offsets to Kafka frequently enough, e.g. consider a loader that places every 100th record to a batch - it would have to reprocess and skip up to 100 records after restart even though it already consumed them before.
Such behavior is inconsistent with all other batchers that always count the full record range, including records that were skipped by the formatting stage. This PR updates the …

Use full record range in partitioned record batch

---

stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/storage/TwoPhaseCommitMetadata.scala

After resetting offsets streamloader fails to recover partitions
```
java.lang.NullPointerException: Cannot invoke "scala.Option.map(scala.Function1)" because "metadata" is null
```

Fix nullpointer bug

---

stream-loader-core/src/main/scala/com/adform/streamloader/source/KafkaSource.scala

We noticed bug where some loaders appeared to have linearly growing watermark.delay.ms. Investigation revealed that after consumer rebalance loaders still emit watermark.delay.ms metric for parition that they not longer consume. This PR adds logic to remove watermark gauge from metric registry after partion revoked event. 
I belive .close() call on removed gauges was meant to remove metric, but this function only invokes empty default implementation form https://github.com/micrometer-metrics/micrometer/blob/1.10.x/micrometer-core/src/main/java/io/micrometer/core/instrument/Meter.java#L483. This method is not overriden in Gauge.

Stale watermark after partition revoked fix

---

stream-loader-tests/src/it/scala/com/adform/streamloader/fixtures/Kafka.scala

pinned kafka image in integration tests to bitnami/kafka:3.4.0-debian-11-r21
bitnami/kafka:3.4.0 image is overwritten on each release. after release r22 integration test stopped working

pin kafka in integration test to working immutable version

---

build.sbt
project/build.properties
project/plugins.sbt
stream-loader-hadoop/src/main/scala/com/adform/streamloader/hadoop/parquet/AvroParquetFileBuilder.scala
stream-loader-hadoop/src/main/scala/com/adform/streamloader/hadoop/parquet/ProtoParquetFileBuilder.scala

Both current `ParquetFileBuilders` write files by specifying a `new hadoop.fs.Path(localTmpFile.toAbsolutePath)` argument. The problem here is that the `Path` class uses whatever Hadoop FS is currently configured as the default (i.e. it checks the value of `fs.defaultFS`). Usually this is not a problem, as the builders use a `new Configuration()` that by default sets `fs.defaultFS = file:///`, however if the app starts with `/etc/hadoop/conf` in it's class path it will load values from `core-site.xml` that can change it. If this happens the built files can get placed to HDFS and then the actual loading to HDFS will fail, because it uses `copyFromLocalFile` (see [here](https://github.com/adform/stream-loader/blob/v0.2.11/stream-loader-hadoop/src/main/scala/com/adform/streamloader/hadoop/Had …

Explicitly use local FS when writing parquet files

---

build.sbt
stream-loader-core/src/main/scala/com/adform/streamloader/sink/file/Compression.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/file/StreamFileBuilder.scala
stream-loader-core/src/test/scala/com/adform/streamloader/sink/file/TimePartitioningFilePathFormatterTest.scala
stream-loader-hadoop/src/main/scala/com/adform/streamloader/hadoop/parquet/ParquetConfig.scala
stream-loader-vertica/src/main/scala/com/adform/streamloader/vertica/file/VerticaFileBuilder.scala

Addresses issue https://github.com/adform/stream-loader/issues/41.
Remove `org.anarres.lzo:lzo-commons` as its GPL-3, drop `Compression.LZOP` support from `StreamFileBuilder`.
Introduced `org.apache.commons.commons-compress` as its needed for `BZip2CompressorOutputStream`. It was transitive dependency for `lzo-commons` as can be seen [here](https://mvnrepository.com/artifact/org.anarres.lzo/lzo-commons/1.0.5)

Remove org.anarres.lzo:lzo-commons as its GPL-3, drop Compression.LZOP

---

build.sbt
project/plugins.sbt
stream-loader-tests/src/test/resources/logback-test.xml
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/ClickHouse.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/Docker.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/Hdfs.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/Kafka.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/S3.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/Vertica.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/storage/ClickHouseStorageBackend.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/storage/HdfsStorageBackend.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/storage/S3StorageBackend.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/storage/StorageBackend.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/storage/VerticaStorageBackend.scala

The Spotify [docker-client](https://github.com/spotify/docker-client) we use for integration tests has been archived for 3 years now and stopped working with latest versions of docker, e.g. Docker 25.0 [removed](https://github.com/moby/moby/pull/45469) the deprecated `virtualSize` field, which this client assumes to exist. Hence we switch to [this fork](https://github.com/dmandalidis/docker-client), which appears to be actively maintained.

Replace spotify docker-client with forked library

---

README.md

The `build` workflow is only run on pull requests, main build only runs `publish`, so this badge is more "correct"

Use publish workflow for build badge

---

build.sbt
project/build.properties
project/plugins.sbt
stream-loader-iceberg/src/main/scala/com/adform/streamloader/iceberg/IcebergRecordBatchStorage.scala
stream-loader-tests/src/main/scala/com/adform/streamloader/loaders/Iceberg.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/ClickHouse.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/storage/IcebergStorageBackend.scala

When multiple threads attempt committing Iceberg transactions to the same table at the same time they can end up conflicting with each other resulting it multiple retries. Even though commits eventually succeed, this can effectively prolong commit times and result in lots of warning messages in logs. Hence we add an option to specify a lock to use when performing commits.
Also:
- fix flaky Iceberg test that randomly failed to download the extension, download it locally once on startup instead
- add a builder for `IcebergRecordBatchStorage`
- bump all libraries
- override `zstd` dependency scheme so that we can bump the patch version

Optional Iceberg commit locks

---

build.sbt
project/build.properties
project/plugins.sbt
stream-loader-core/src/main/scala/com/adform/streamloader/util/UuidExtensions.scala
stream-loader-core/src/test/scala/com/adform/streamloader/util/UuidExtensionsTest.scala
stream-loader-iceberg/src/main/scala/com/adform/streamloader/iceberg/IcebergRecordBatcher.scala

We use UUID based filenames when creating Iceberg files, which is technically fine, but annoying in practice because the files are not sorted. The [UUIDv7](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_7_(timestamp_and_random)) specification is timestamp based, so guarantees that values generated 1ms apart are alphabetically sorted, hence we switch to that.
Also, obligatory version bump.

Use UUIDv7 based Iceberg file names

---

build.sbt
project/build.properties
project/plugins.sbt
stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/RecordBatchingSinker.scala
stream-loader-core/src/main/scala/com/adform/streamloader/util/Metrics.scala

Currently only the last consumed watermark is being exposed as a metric, which is not the full story, as it does not tell anything about the actual data freshness in the sink. Hence we add a new metric for tracking watermarks per partition that only gets updated when data actually gets sinked.
Also bumping all versions.

Add metrics for last committed watermarks

---

stream-loader-core/src/main/scala/com/adform/streamloader/sink/file/FileCommitStrategy.scala
stream-loader-core/src/test/scala/com/adform/streamloader/sink/file/FileCommitStrategyTest.scala

Currently the `RecordBatchingSinker` checks whether a batch should be finalized after processing every record, to do that it passes the current record count and the current file size to a given `FileCommitStrategy`. The problem is that estimating the file size for formats like `parquet` can be very expensive, we observe ~15% of total time spent there. In addition, the file size in case of `parquet` is only an estimate, so doing it so frequently is pointless.
We thus change the interface of `FileCommitStrategy` to accept the file size lazily, i.e. if the strategy does not invoke it, it will not be calculated. In addition we tune `FuzzyReachedAnyOf` to have a configurable `fileSizeSamplingBatchSize`, i.e. a number of records processed that triggers a file size check (e.g. every 1000 …

Add ability to estimate file size lazily

---

build.sbt
project/plugins.sbt
stream-loader-core/src/main/scala/com/adform/streamloader/model/StreamRange.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/RecordBatch.scala
stream-loader-core/src/main/scala/com/adform/streamloader/sink/batch/RecordBatchingSinker.scala
stream-loader-core/src/test/scala/com/adform/streamloader/model/StreamRangeTest.scala
stream-loader-iceberg/src/main/scala/com/adform/streamloader/iceberg/IcebergRecordBatcher.scala
stream-loader-tests/src/main/resources/application-iceberg.conf
stream-loader-tests/src/main/scala/com/adform/streamloader/loaders/Iceberg.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/IcebergIntegrationTests.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/behaviors/BasicLoaderBehaviors.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/ClickHouse.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/Kafka.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/S3.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/fixtures/Vertica.scala
stream-loader-tests/src/test/scala/com/adform/streamloader/storage/IcebergStorageBackend.scala

**Motivation**
The current batch committing algorithm works by preparing record batches, adding them to a FIFO blocking queue and running a separate batch commit thread that takes batches sequentially one-by-once and commits them to storage. The queue size is configurable and once reached the sink is blocked until it clears up.
In high throughput situations the sink may end up forming lots of batches (either because they're too small or there's too much data) and invoking commits faster than the storage can keep up with. This becomes a bottleneck for the loader and is detrimental to the storage too, as there's lots of activity.
Some storages, e.g. Iceberg, support batch merging, i.e. a single batch contains a list of files, so merging batches simply amounts to unioning files from all the …

Record batch merging

---

.github/workflows/publish.yml
build.sbt
project/BuildSettings.scala
project/build.properties
project/plugins.sbt
publish.sbt
stream-loader-tests/src/test/scala/com/adform/streamloader/VerticaIntegrationTests.scala

As of June 30, 2025 OSSRH has reached end of life and has been shut down. All OSSRH namespaces have been migrated to Central Publisher Portal.

Use Maven Central Publisher Portal
